# Generated by Django 5.0.3 on 2024-03-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Location Name')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.CharField(default=1, max_length=50, verbose_name='Business Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Business Email'),
        ),
        migrations.AddField(
            model_name='business',
            name='founding_date',
            field=models.DateField(blank=True, null=True, verbose_name='Founding Date'),
        ),
        migrations.AddField(
            model_name='business',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Business Phone Number'),
        ),
        migrations.AddField(
            model_name='business',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Annual Revenue'),
        ),
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True, verbose_name='Business Website'),
        ),
        migrations.AlterField(
            model_name='business',
            name='certificate_details',
            field=models.FileField(upload_to='certificate_details/', verbose_name='Certificate Details'),
        ),
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(verbose_name='Business Description'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Business Name'),
        ),
        migrations.AddField(
            model_name='business',
            name='locations',
            field=models.ManyToManyField(related_name='businesses', to='loan.businesslocation', verbose_name='Business Locations'),
        ),
    ]
